[package]

name = "fontconfig-sys"
version = "2.11.0"
authors = ["Keith Packard <keithp@keithp.com>", "Patrick Lam <plam@mit.edu>"]

build = "make -f makefile.cargo"

[lib]

name = "fontconfig-sys"
path = "lib.rs"

[dependencies.expat-sys]
git = "https://github.com/servo/libexpat"

[dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

